services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=ujyech
        - POSTGRES_DB=Code
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db