"""auth and sign

Revision ID: 078348dc194c
Revises: 716e091252d5
Create Date: 2024-08-30 12:14:38.370269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078348dc194c'
down_revision: Union[str, None] = '716e091252d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notes_id', table_name='notes')
    op.drop_index('ix_notes_text', table_name='notes')
    op.drop_table('notes')
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.drop_index('ix_users_age', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    op.drop_column('users', 'age')
    op.drop_column('users', 'family')
    op.drop_column('users', 'mail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mail', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('family', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_age', 'users', ['age'], unique=False)
    op.drop_column('users', 'username')
    op.create_table('notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='notes_pkey')
    )
    op.create_index('ix_notes_text', 'notes', ['text'], unique=False)
    op.create_index('ix_notes_id', 'notes', ['id'], unique=False)
    # ### end Alembic commands ###
