"""3 commit

Revision ID: 716e091252d5
Revises: ce9cc39e9969
Create Date: 2024-08-30 11:15:33.790528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716e091252d5'
down_revision: Union[str, None] = 'ce9cc39e9969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_family', table_name='users')
    op.drop_index('ix_users_mail', table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_index('ix_users_mail', 'users', ['mail'], unique=False)
    op.create_index('ix_users_family', 'users', ['family'], unique=False)
    # ### end Alembic commands ###
